# Generated by Django 4.1.5 on 2023-03-08 15:35

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items_buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_phone', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[100, 100], upload_to='for_sell/', verbose_name='Фотография модели телефона')),
                ('model_produkt', models.TextField(max_length=80, verbose_name='Модель продукта ')),
                ('text', models.TextField(max_length=500, verbose_name='Текст')),
                ('max_prise', models.FloatField(verbose_name='Максимальная цена telefoha')),
                ('image_phone_for_buy_bord', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[100, 100], upload_to='for_sell/', verbose_name='Фотография модели телефона ha prodazy')),
            ],
            options={
                'verbose_name': 'Телефон который покупаем',
                'verbose_name_plural': 'Телефоны которые покупаем',
                'db_table': 'items_buy',
            },
        ),
        migrations.CreateModel(
            name='Items_buy_planset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_planset', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[100, 100], upload_to='for_sell/', verbose_name='Фотография модели Планшета')),
                ('model_produkt', models.TextField(max_length=80, verbose_name='Модель продукта ')),
                ('text', models.TextField(max_length=500, verbose_name='Текст')),
                ('max_prise', models.FloatField(verbose_name='Максимальная цена Планшета')),
                ('image_planset_for_buy_bord', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[100, 100], upload_to='for_sell/', verbose_name='Фотография модели Планшета ha prodazy')),
            ],
            options={
                'verbose_name': 'Планшет который покупаем',
                'verbose_name_plural': 'Планшеты которые покупаем',
                'db_table': 'items_buy_planset',
            },
        ),
        migrations.CreateModel(
            name='Items_buy_watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_watch', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[100, 100], upload_to='for_sell/', verbose_name='Фотография модели watch')),
                ('model_produkt', models.TextField(max_length=80, verbose_name='Модель продукта ')),
                ('text', models.TextField(max_length=500, verbose_name='Текст')),
                ('max_prise', models.FloatField(verbose_name='Максимальная цена watch')),
                ('image_watch_for_buy_bord', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[100, 100], upload_to='for_sell/', verbose_name='Фотография модели watch ha prodazy')),
            ],
            options={
                'verbose_name': 'watch который покупаем',
                'verbose_name_plural': 'watches которые покупаем',
                'db_table': 'items_buy_watch',
            },
        ),
        migrations.CreateModel(
            name='Question_phone_glavhaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'glavhii voprosi dla telefona',
                'verbose_name_plural': 'glavhii voprosi dla telefona',
                'db_table': 'question_phone_glavhaya',
            },
        ),
        migrations.CreateModel(
            name='Question_planset_glavhaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'glavhii voprosi dla planset',
                'verbose_name_plural': 'glavhii voprosi dla planset',
                'db_table': 'question_planset_glavhaya',
            },
        ),
        migrations.CreateModel(
            name='Question_watch_glavhaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'glavhii voprosi dla watch',
                'verbose_name_plural': 'glavhii voprosi dla watchs',
                'db_table': 'question_watch_glavhaya',
            },
        ),
        migrations.CreateModel(
            name='Question_watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(max_length=150, verbose_name='Заголовок вопросa')),
                ('question_text', models.TextField(max_length=100, verbose_name='Заголовок вопросa text')),
                ('items_buy_watch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='project_1.items_buy_watch')),
            ],
            options={
                'verbose_name': 'Вопрос к Планшетy',
                'verbose_name_plural': 'Вопросы к Планшетy',
                'db_table': 'question_watch',
            },
        ),
        migrations.CreateModel(
            name='Question_planset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(max_length=150, verbose_name='Заголовок вопросa')),
                ('question_text', models.TextField(max_length=100, verbose_name='Заголовок вопросa text')),
                ('items_buy_planset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='project_1.items_buy_planset')),
            ],
            options={
                'verbose_name': 'Вопрос к Планшетy',
                'verbose_name_plural': 'Вопросы к Планшетy',
                'db_table': 'question_planset',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(max_length=150, verbose_name='Заголовок вопросa')),
                ('question_text', models.TextField(max_length=100, verbose_name='Заголовок вопросa text')),
                ('items_buy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='project_1.items_buy')),
            ],
            options={
                'verbose_name': 'Вопрос к телефону',
                'verbose_name_plural': 'Вопросы к телефону',
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Orders_watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ваше имя', max_length=50, verbose_name='Имя продавьца')),
                ('gmail', models.EmailField(help_text='Ваша электронная почта', max_length=254, verbose_name='Почта продавьца')),
                ('phone_nomber', phonenumber_field.modelfields.PhoneNumberField(help_text='Ваш номер телефона', max_length=128, region=None, verbose_name='Номер телефона продавьца')),
                ('image1', models.ImageField(help_text='foto nomber1 ', upload_to='for_client/', verbose_name='Фотографии к телефону 1')),
                ('image2', models.ImageField(help_text='foto nomber2', upload_to='for_client/', verbose_name='Фотографии к телефону 2')),
                ('image3', models.ImageField(help_text='foto nomber3', upload_to='for_client/', verbose_name='Фотографии к телефону 3')),
                ('image4', models.ImageField(help_text='foto nomber4', upload_to='for_client/', verbose_name='Фотографии к телефону 4')),
                ('image5', models.ImageField(help_text='foto nomber5', upload_to='for_client/', verbose_name='Фотографии к телефону 5')),
                ('image6', models.ImageField(help_text='foto nomber6', upload_to='for_client/', verbose_name='Фотографии к телефону 6')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа на продажу')),
                ('items_buy_watch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='project_1.items_buy_watch')),
            ],
            options={
                'verbose_name': 'Заказ на продажу watch',
                'verbose_name_plural': 'Заказi на продажi watch',
                'db_table': 'orders_for_sell_watch',
            },
        ),
        migrations.CreateModel(
            name='Orders_planset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ваше имя', max_length=50, verbose_name='Имя продавьца')),
                ('gmail', models.EmailField(help_text='Ваша электронная почта', max_length=254, verbose_name='Почта продавьца')),
                ('phone_nomber', phonenumber_field.modelfields.PhoneNumberField(help_text='Ваш номер телефона', max_length=128, region=None, verbose_name='Номер телефона продавьца')),
                ('image1', models.ImageField(help_text='foto nomber1 ', upload_to='for_client/', verbose_name='Фотографии к телефону 1')),
                ('image2', models.ImageField(help_text='foto nomber2', upload_to='for_client/', verbose_name='Фотографии к телефону 2')),
                ('image3', models.ImageField(help_text='foto nomber3', upload_to='for_client/', verbose_name='Фотографии к телефону 3')),
                ('image4', models.ImageField(help_text='foto nomber4', upload_to='for_client/', verbose_name='Фотографии к телефону 4')),
                ('image5', models.ImageField(help_text='foto nomber5', upload_to='for_client/', verbose_name='Фотографии к телефону 5')),
                ('image6', models.ImageField(help_text='foto nomber6', upload_to='for_client/', verbose_name='Фотографии к телефону 6')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа на продажу')),
                ('items_buy_planset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='project_1.items_buy_planset')),
            ],
            options={
                'verbose_name': 'Заказ на продажу planset',
                'verbose_name_plural': 'Заказi на продажi planset',
                'db_table': 'orders_for_sell_planset',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ваше имя', max_length=50, verbose_name='Имя продавьца')),
                ('gmail', models.EmailField(help_text='Ваша электронная почта', max_length=254, verbose_name='Почта продавьца')),
                ('phone_nomber', phonenumber_field.modelfields.PhoneNumberField(help_text='Ваш номер телефона', max_length=128, region=None, verbose_name='Номер телефона продавьца')),
                ('image1', models.ImageField(help_text='foto nomber1 ', upload_to='for_client/', verbose_name='Фотографии к телефону 1')),
                ('image2', models.ImageField(help_text='foto nomber2', upload_to='for_client/', verbose_name='Фотографии к телефону 2')),
                ('image3', models.ImageField(help_text='foto nomber3', upload_to='for_client/', verbose_name='Фотографии к телефону 3')),
                ('image4', models.ImageField(help_text='foto nomber4', upload_to='for_client/', verbose_name='Фотографии к телефону 4')),
                ('image5', models.ImageField(help_text='foto nomber5', upload_to='for_client/', verbose_name='Фотографии к телефону 5')),
                ('image6', models.ImageField(help_text='foto nomber6', upload_to='for_client/', verbose_name='Фотографии к телефону 6')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа на продажу')),
                ('items_buy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='project_1.items_buy')),
            ],
            options={
                'verbose_name': 'Заказ на продажу',
                'verbose_name_plural': 'Заказi на продажi',
                'db_table': 'orders_for_sell',
            },
        ),
        migrations.CreateModel(
            name='Choice_watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок выбора')),
                ('price_question', models.FloatField(verbose_name='Цена ответа')),
                ('question_watch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='options', to='project_1.question_watch')),
            ],
            options={
                'verbose_name': 'Выбор ответа watch',
                'verbose_name_plural': 'Выбор ответов watch',
                'db_table': 'choice_watch',
            },
        ),
        migrations.CreateModel(
            name='Choice_planset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок выбора')),
                ('price_question', models.FloatField(verbose_name='Цена ответа')),
                ('question_planset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='options', to='project_1.question_planset')),
            ],
            options={
                'verbose_name': 'Выбор ответа planset',
                'verbose_name_plural': 'Выбор ответов planseta',
                'db_table': 'choice_planset',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок выбора')),
                ('price_question', models.FloatField(verbose_name='Цена ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='options', to='project_1.question')),
            ],
            options={
                'verbose_name': 'Выбор ответа',
                'verbose_name_plural': 'Выбор ответов',
                'db_table': 'choice',
            },
        ),
        migrations.CreateModel(
            name='Answer_watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('choice_watch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='project_1.choice_watch')),
                ('items_buy_watch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='project_1.items_buy_watch')),
                ('question_watch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='project_1.question_watch')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос watch',
                'verbose_name_plural': 'Ответы на вопросы watch',
                'db_table': 'answer_watch',
            },
        ),
        migrations.CreateModel(
            name='Answer_planset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('choice_planset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='project_1.choice_planset')),
                ('items_buy_planset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='project_1.items_buy_planset')),
                ('question_planset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='project_1.question_planset')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос planset',
                'verbose_name_plural': 'Ответы на вопросы planset',
                'db_table': 'answer_planset',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='project_1.choice')),
                ('items_buy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='project_1.items_buy')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='project_1.question')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы',
                'db_table': 'answer',
            },
        ),
    ]
