# Generated by Django 4.1.5 on 2023-03-08 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question_phone_glavhaya',
        ),
        migrations.DeleteModel(
            name='Question_planset_glavhaya',
        ),
        migrations.DeleteModel(
            name='Question_watch_glavhaya',
        ),
    ]
