# Generated by Django 4.1.5 on 2023-03-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_1', '0002_delete_question_phone_glavhaya_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(max_length=200, verbose_name='Заголовок вопросa text'),
        ),
    ]
