# Generated by Django 4.1.5 on 2023-03-19 21:45

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('project_1', '0003_alter_question_question_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone_Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='price Phone')),
                ('model', models.TextField(max_length=100, verbose_name='Модель продукта ha prodazy')),
                ('membory', models.TextField(max_length=6, verbose_name='membory for Phone')),
                ('color', models.TextField(verbose_name='color phone')),
                ('stan_telefohy', models.TextField(verbose_name='Стан телефону')),
                ('text', models.TextField(verbose_name='text description for Phone')),
            ],
            options={
                'verbose_name': 'Телефон который prodaem',
                'verbose_name_plural': 'Телефоны которые prodaem',
                'db_table': 'phone_sell',
            },
        ),
        migrations.CreateModel(
            name='Planset_Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='price Planset')),
                ('model', models.TextField(max_length=100, verbose_name='Модель продукта ha prodazy')),
                ('membory', models.TextField(max_length=6, verbose_name='membory for Planset')),
                ('color', models.TextField(verbose_name='color phone')),
                ('stan_telefohy', models.TextField(verbose_name='Стан Planset')),
                ('text', models.TextField(verbose_name='text description for Planset')),
            ],
            options={
                'verbose_name': 'Planset который prodaem',
                'verbose_name_plural': 'Planset которые prodaem',
                'db_table': 'phone_planset',
            },
        ),
        migrations.CreateModel(
            name='Watch_Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='price watch')),
                ('model', models.TextField(max_length=100, verbose_name='Модель продукта ha watch')),
                ('membory', models.TextField(max_length=6, verbose_name='membory for watch')),
                ('color', models.TextField(verbose_name='color watch')),
                ('stan_telefohy', models.TextField(verbose_name='Стан watch')),
                ('text', models.TextField(verbose_name='text description for watch')),
            ],
            options={
                'verbose_name': 'watch который pokypaem',
                'verbose_name_plural': 'watch которые pakypaem',
                'db_table': 'watch_sell',
            },
        ),
        migrations.CreateModel(
            name='Photo_Watch_Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='for_buy/')),
                ('watch_sell_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_1.watch_sell')),
            ],
        ),
        migrations.CreateModel(
            name='Photo_Planset_Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='for_buy/')),
                ('planset_sell_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_1.planset_sell')),
            ],
        ),
        migrations.CreateModel(
            name='Photo_Phone_Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='for_buy/')),
                ('phone_sell_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_1.phone_sell')),
            ],
        ),
        migrations.CreateModel(
            name='Order_watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='ima')),
                ('famili', models.TextField(max_length=50, verbose_name='familia')),
                ('mail', models.EmailField(max_length=254, verbose_name='posta')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='nomer planset')),
                ('sposob_dostavki', models.TextField(verbose_name='sposob_oplati')),
                ('gorod', models.TextField(verbose_name='gorod')),
                ('nomber_viddilehha', models.TextField(verbose_name='nomer_viddilehha')),
                ('sposob_oplati', models.TextField(verbose_name='sposob_oplati')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создания заказа на zakaza')),
                ('phone_sell_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_1.watch_sell')),
            ],
            options={
                'verbose_name': 'zaiavki ha pokypky watch',
                'verbose_name_plural': 'zaiavki ha pokypky watch',
                'db_table': 'order_watch',
            },
        ),
        migrations.CreateModel(
            name='Order_planset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='ima')),
                ('famili', models.TextField(max_length=50, verbose_name='familia')),
                ('mail', models.EmailField(max_length=254, verbose_name='posta')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='nomer planset')),
                ('sposob_dostavki', models.TextField(verbose_name='sposob_oplati')),
                ('gorod', models.TextField(verbose_name='gorod')),
                ('nomber_viddilehha', models.TextField(verbose_name='nomer_viddilehha')),
                ('sposob_oplati', models.TextField(verbose_name='sposob_oplati')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создания заказа на zakaza')),
                ('phone_sell_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_1.planset_sell')),
            ],
            options={
                'verbose_name': 'zaiavki ha pokypky planset',
                'verbose_name_plural': 'zaiavki ha pokypky planset',
                'db_table': 'order_planset',
            },
        ),
        migrations.CreateModel(
            name='Order_phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='ima')),
                ('famili', models.TextField(max_length=50, verbose_name='familia')),
                ('mail', models.EmailField(max_length=254, verbose_name='posta')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='nomer telefoha')),
                ('sposob_dostavki', models.TextField(verbose_name='sposob_oplati')),
                ('gorod', models.TextField(verbose_name='gorod')),
                ('nomber_viddilehha', models.TextField(verbose_name='nomer_viddilehha')),
                ('sposob_oplati', models.TextField(verbose_name='sposob_oplati')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создания заказа на zakaza')),
                ('phone_sell_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_1.phone_sell')),
            ],
            options={
                'verbose_name': 'zaiavki ha pokypky telefoha',
                'verbose_name_plural': 'zaiavki ha pokypky telefohiv',
                'db_table': 'order_phone',
            },
        ),
    ]
