# Generated by Django 4.1.5 on 2023-03-20 00:22

import datetime
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('project_1', '0004_phone_sell_planset_sell_watch_sell_photo_watch_sell_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone_sell',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default=datetime.date.today, force_format=None, keep_meta=True, quality=-1, scale=None, size=[100, 100], upload_to='for_buy/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planset_sell',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default=datetime.date.today, force_format=None, keep_meta=True, quality=-1, scale=None, size=[100, 100], upload_to='for_buy/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watch_sell',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default=datetime.date.today, force_format=None, keep_meta=True, quality=-1, scale=None, size=[100, 100], upload_to='for_buy/'),
            preserve_default=False,
        ),
    ]
