# Generated by Django 4.1.5 on 2023-03-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_1', '0005_phone_sell_image_planset_sell_image_watch_sell_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone_sell',
            name='image',
            field=models.ImageField(upload_to='for_buy/'),
        ),
    ]
