# Generated by Django 4.1.5 on 2023-03-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_1', '0008_alter_phone_sell_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone_sell',
            name='image',
            field=models.FileField(upload_to='for_buy/'),
        ),
    ]
