# Generated by Django 4.1.5 on 2023-03-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_1', '0010_phone_sell_paragraph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone_sell',
            name='paragraph',
        ),
    ]
