# Generated by Django 4.1.5 on 2023-04-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_1', '0011_remove_phone_sell_paragraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone_sell',
            name='membory',
            field=models.TextField(choices=[('32gb', '32gb'), ('64gb', '64gb'), ('128gb', '128gb')], max_length=6, verbose_name='membory for Phone'),
        ),
    ]
